// To make this work without file system , we define a header file that keeps our kernel clean.

#ifndef COUNTRIES_H
#define COUNTRIES_H

#define TOTAL_COUNTRIES 187

struct Country 
{
    char* name;
    char* food;
    char* culture;
};

// We can add more countries as build
struct Country world_map[TOTAL_COUNTRIES] = 
{
    {"Afghanistan", "Kabuli Pulao", "Attan Dance"},
    {"Albania", "Tavë Kosi", "Iso-Polyphony"},
    {"Algeria", "Couscous", "Raï Music"},
    {"Andorra", "Escudella", "Sardana Dance"},
    {"Angola", "Moamba de Galinha", "Kizomba Dance"},
    {"Argentina", "Asado", "Tango Dance"},
    {"Armenia", "Khorovats", "Armenian Duduk Music"},
    {"Australia", "Meat Pie", "Aboriginal Dreamtime Stories"},
    {"Austria", "Wiener Schnitzel", "Viennese Waltz"},
    {"Azerbaijan", "Plov", "Mugham Music"},
    {"Bahamas", "Cracked Conch", "Junkanoo Festival"},
    {"Bahrain", "Machboos", "Ardha Dance"},
    {"Bangladesh", "Hilsa Fish Curry", "Baul Music"},
    {"Barbados", "Flying Fish and Cou-Cou", "Crop Over Festival"},
    {"Belarus", "Draniki", "Belarusian Flok Music"},
    {"Belgium", "Moules-Frites", "Carnival of Binche"},
    {"Belize", "Rice and Beans", "Garifuna Drumming"},
    {"Benin", "Amiwo", "Vodun Rituals"},
    {"Bhutan", "Ema Datshi", "Traditional Mask Dance"},
    {"Bolivia", "Salteñas", "Diablada Dance"},
    {"Bosnia and Herzegovina", "Cevapi", "Bosnian Folk Music"},
    {"Botswana", "Seswaa", "Tswana Traditional Dance"},
    {"Brazil", "Feijoada", "Samba Dance"},
    {"Brunei", "Nasi Lemak", "Silat Martial Arts"},
    {"Bulgaria", "Banitsa", "Horo Dance"},
    {"Burkina Faso", "Ragout d'Igname", "Balafon Music"},
    {"Burundi", "Isombe", "Burundi Drumming"},
    {"Cambodia", "Amok Trey", "Apsara Dance"},
    {"Cameroon", "Ndole", "Makossa Music"},
    {"Canada", "Poutine", "Indigenous Powwow Dance"},
    {"Cape Verde", "Cachupa", "Morna Music"},
    {"Central African Republic", "Muamba de Galinha", "Traditional Dance"},
    {"Chad", "Jarret de Boeuf", "Sara Traditional Dance"},
    {"Chile", "Empanadas", "Cueca Dance"},
    {"China", "Peking Duck", "Chinese Opera"},
    {"Colombia", "Arepas", "Cumbia Dance"},
    {"Comoros", "Langouste a la Vanille", "M' godra Dance"},
    {"Congo", "Poulet Moambe", "Soukous Music"},
    {"Costa Rica", "Gallo Pinto", "Punto Guanacasteco Dance"},
    {"Croatia", "Pasticada", "Kolo Dance"},
    {"Cuba", "Ropa Vieja", "Salsa Dance"},
    {"Cyprus", "Halloumi Cheese", "Cypriot Folk Dance"},
    {"Czech Republic", "Svíčková", "Polka Dance"},
    {"Denmark", "Smørrebrød", "Danish Folk Dance"},
    {"Djibouti", "Skoudehkaris", "Traditional Dance"},
    {"Dominica", "Mountain Chicken", "Quadrille Dance"},
    {"Dominican Republic", "Mangu", "Merengue Dance"},
    {"Ecuador", "Ceviche", "Pasillo Music"},
    {"Egypt", "Koshari", "Belly Dance"},
    {"El Salvador", "Pupusas", "Xuc Dance"},
    {"Equatorial Guinea", "Succotash", "Traditional Dance"},
    {"Eritrea", "Zigni", "Tigrinya Music"},
    {"Estonia", "Verivorst", "Seto Leelo Singing"},
    {"Eswatini", "Sishwala", "Umhlanga Reed Dance"},
    {"Ethiopia", "Doro Wat", "Eskista Dance"},
    {"Fiji", "Kokoda", "Meke Dance"},
    {"Finland", "Karjalanpiirakka", "Jenkka Dance"},
    {"France", "Coq au Vin", "Can-Can Dance"},
    {"Gabon", "Nyembwe Chicken", "Bwiti Music"},
    {"Gambia", "Domoda", "Kora Music"},
    {"Georgia", "Khachapuri", "Kartuli Dance"},
    {"Germany", "Bratwurst", "Schuhplattler Dance"},
    {"Ghana", "Jollof Rice", "Adowa Dance"},
    {"Greece", "Moussaka", "Sirtaki Dance"},
    {"Grenada", "Oil Down", "Big Drum Dance"},
    {"Gautemale", "Pepian", "Marimba Music"},
    {"Guinea", "Poulet Yassa", "Djembe Drumming"},
    {"Guinea-Bissau", "Caldo de Peixe", "Balanta Dance"},
    {"Guyana", "Pepperpot", "Shanto Music"},
    {"Haiti", "Griot", "Rara Music"},
    {"Honduras", "Baleadas", "Punta Dance"},
    {"Hungary", "Gulyás", "Csárdás Dance"},
    {"Iceland", "Hákarl", "Rímur Singing"},
    {"India", "Biryani", "Bharatanatyam Dance"},
    {"Indonesia", "Nasi Goreng", "Balinese Dance"},
    {"Iran", "Chelo Kebab", "Persian Classical Music"},
    {"Iraq", "Masgouf", "Chobi Dance"},
    {"Ireland", "Irish Stew", "Irish Stepdance"},
    {"Israel", "Shakshuka", "Hora Dance"},
    {"Italy", "Pizza", "Tarantella Dance"},
    {"Jamaica", "Ackee and Saltfish", "Reggae Music"},
    {"Japan", "Sushi", "Kabuki Theatre"},
    {"Jordan", "Mansaf", "Dabke Dance"},
    {"Kazakhstan", "Beshbarmak", "Kuy Music"},
    {"Kenya", "Nyama Choma", "Sukuma Dance"},
    {"Kiribati", "Palusami", "Te Kaimatoa Dance"},
    {"Kuwait", "Machboos", "Ardha Dance"},
    {"Kyrgyzstan", "Beshbarmak", "Kyrgyz Epic Poetry"},
    {"Laos", "Larb", "Lam Vong Dance"},
    {"Latvia", "Grey Peas and Ham", "Dainas Singing"},
    {"Lebanon", "Tabbouleh", "Dabke Dance"},
    {"Lesotho", "Papa and Moroho", "Mokhibo Dance"},
    {"Liberia", "Palm Butter Soup", "Gola Dance"},
    {"Libya", "Bazeen", "Tuareg Camel Festival"},
    {"Liechtenstein", "Käsknöpfle", "Alpabfahrt Cattle Drive"},
    {"Lithuania", "Cepelinai", "Joninės Midsummer"},
    {"Luxembourg", "Judd mat Gaardebounen", "Echternach Dancing Procession"},
    {"Madagascar", "Romazava", "Famadihana Turning Bones"},
    {"Malawi", "Chambo with Nsima", "Gule Wamkulu Dance"},
    {"Malaysia", "Nasi Lemak", "Hari Raya Celebrations"},
    {"Maldives", "Garudhiya", "Bodu Beru Drumming"},
    {"Mali", "Tigadegena", "Dogon Mask Dance"},
    {"Malta", "Pastizzi", "Village Festa"},
    {"Marshall Islands", "Barramundi Cod", "Kajin Majel Chants"},
    {"Mauritania", "Thieboudienne", "Nomadic Tea Ritual"},
    {"Mauritius", "Dholl Puri", "Sega Dance"},
    {"Mexico", "Tacos", "Day of the Dead"},
    {"Micronesia", "Sakit", "Yapese Stone Money"},
    {"Moldova", "Mămăligă", "Mărțișor Spring Festival"},
    {"Monaco", "Barbajuan", "National Day Parade"},
    {"Mongolia", "Buuz", "Naadam Festival"},
    {"Montenegro", "Njegoški Pršut", "Slava Feast"},
    {"Morocco", "Tagine", "Mint Tea Ritual"},
    {"Mozambique", "Galinda Piri-Piri", "Mapiko Mask Dance"},
    {"Myanmar", "Mohinga", "Thingyan Water Festival"},
    {"Namibia", "Kapana", "Herero Dress Parade"},
    {"Nauru", "Coconut Crustacean", "Angam Day"},
    {"Nepal", "Dal Bhat", "Dashain Festival"},
    {"Netherlands", "Stroopwafel", "King's Day"},
    {"New Zealand", "Hāngī", "Haka Dance"},
    {"Nicaragua", "Gallo Pinto", "El Güegüense Drama"},
    {"Niger", "Djerma Stew", "Cure Salée Festival"},
    {"Nigeria", "Jollof Rice", "New Yam Festival"},
    {"North Macedonia", "Tavče Gravče", "Galičnik Wedding Festival"},
    {"Norway", "Fårikål", "Friluftsliv Outdoor Life"},
    {"Oman", "Shuwa", "Frankincense Burning"},
    {"Pakistan", "Nihari", "Sufi Qawwali Music"},
    {"Palau", "Fruit Bat Soup", "First Birth Ceremony"},
    {"Panama", "Sancocho", "Pollera Dress Parade"},
    {"Papua New Guinea", "Mumu", "Sing-Sing Gathering"},
    {"Paraguay", "Sopa Paraguaya", "Tereré Drinking Circle"},
    {"Peru", "Ceviche", "Inti Raymi Sun Festival"},
    {"Philippines", "Adobo", "Bayanihan Community Spirit"},
    {"Poland", "Pierogi", "Śmigus-Dyngus"},
    {"Portugal", "Bacalhau", "Fado Music"},
    {"Qatar", "Machboos", "Falconry Culture"},
    {"Romania", "Sarmale", "Mărțișor Tradition"},
    {"Russia", "Borscht", "Maslenitsa Pancake Week"},
    {"Rwanda", "Isombe", "Kwita Izina Naming"},
    {"Saint Kitts and Nevis", "Goat Water", "Sugar Mas Carnival"},
    {"Saint Lucia", "Green Fig and Saltfish", "La Rose Flower Festival"},
    {"Samoa", "Oka", "Siva Samoa Dance"},
    {"San Marino", "Torta Tre Monti", "Crossbowmen Tournament"},
    {"Saudi Arabia", "Kabsa", "Ardha Sword Dance"},
    {"Senegal", "Thieboudienne", "Sabau Drumming"},
    {"Serbia", "Ćevapi", "Slava Patron Saint Day"},
    {"Seychelles", "Ladob", "Kreol Festival"},
    {"Sierra Leone", "Cassava Leaf Stew", "Poro Mask Society"},
    {"Singapore", "Chilli Crab", "Hawker Culture"},
    {"Slovakia", "Bryndzové Halušky", "Fasiangy Carnival"},
    {"Slovenia", "Potica", "Kurentovanje Carnival"},
    {"Solomon Islands", "Poi", "Shell Money Currency"},
    {"Somalia", "Bariis Iskukaris", "Gabi Chanting"},
    {"South Africa", "Braai", "Gumboot Dancing"},
    {"South Korea", "Kimchi", "Chuseok Festival"},
    {"Spain", "Paella", "Flamenco Dance"},
    {"Sri Lanka", "Kottu Roti", "Esala Perahera"},
    {"Sudan", "Ful Medames", "Sufi Whirling dervishes"},
    {"Suriname", "Pom", "Keti Koti Celebration"},
    {"Sweden", "Köttbullar", "Midsommar Pole Dancing"},
    {"Switzerland", "Fondue", "Yodeling Festivals"},
    {"Syria", "Shawarma", "Dervish Dance"},
    {"Taiwan", "Beef Noodle Soup", "Lantern Festival"},
    {"Tajikistan", "Plov", "Sayri Guli Lola"},
    {"Tanzania", "Ugali", "Nyama Choma Gatherings"},
    {"Thailand", "Pad Thai", "Songkran Water Festival"},
    {"Togo", "Fufu", "Evala Wrestling"},
    {"Tonga", "Lu Pulu", "Kava Ceremony"},
    {"Trinidad and Tobago", "Doubles", "Steelpan Carnival"},
    {"Tunisia", "Couscous", "Jasmine Festival"},
    {"Turkey", "Kebab", "Turkish Coffee Fortune Telling"},
    {"Turkmenistan", "Plov", "Akhal-Teke Horse Parade"},
    {"Tuvalu", "Pulaka", "Fatele Dance"},
    {"Uganda", "Matooke", "Imbalu Circumcision Ceremony"},
    {"Ukraine", "Borscht", "Vyshyvanka Day"},
    {"United Arab Emirates", "Harees", "Al-Ayyala Dance"},
    {"United Kingdom", "Fish and Chips", "Sunday Roast"},
    {"United States", "Hamburger", "Thanksgiving Dinner"},
    {"Uruguay", "Chivito", "Mate Drinking Circle"},
    {"Uzbekistan", "Plov", "Kupkari Horse Sport"},
    {"Vanuatu", "Laplap", "Naghol Land Diving"},
    {"Vatican City", "Fettuccine alla Papalina", "Easter Urbi et Orbi"},
    {"Venezuela", "Arepas", "Dancing Devils of Yare"},
    {"Vietnam", "Pho", "Mid-Autumn Festival"},
    {"Yemen", "Mandi", "Kat Chewing Gatherings"},
    {"Zambia", "Nshima", "Kuomboka Festival"},
    {"Zimbabwe", "Sadza", "Mbira Music Spirit"},
};

#endif